url = 'https://www.houzz.com/professionals/general-contractor/brentwood-los-angeles-ca-us-probr0-bo~t_11786~r_101182514'
next_page_css_selector = 'a.hz-pagination-link--next'
businesses_class = 'hz-pro-search-results__item'